import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
    	double minPrice=1000;
    	double totalPrice=0;
    	int flag=0;
    	List<String> menu =new ArrayList<String>();//点单中的菜品
    	List<Integer> number =new ArrayList<Integer>();//菜品数量
    	List<String> idOfAll_Item =new ArrayList<String>();//ALL_Item中的菜品编号
    	List<String> relatedItemsOfALL_SALES_PROMOTIONS =new ArrayList<String>();//指定菜品
    	for(String str:inputs) {
    		String s[]=str.split(" ");
    		menu.add(s[0]);
    		number.add(Integer.valueOf(s[2]));
    	}
    	for(Item item:this.itemRepository.findAll()) {//将item里的id取出来
    		idOfAll_Item.add(item.getId());
    	}
    	int i=0;
    	for(String str:menu) {//计算没有优惠的价格
    		totalPrice=totalPrice+(this.itemRepository.findAll().get(idOfAll_Item.indexOf(str)).getPrice())*number.get(i);
    		i++;
    	}
        //将ALL_SALES_PROMOTIONS里的relateditem取出来
    	relatedItemsOfALL_SALES_PROMOTIONS=this.salesPromotionRepository.findAll().get(1).getRelatedItems();
    	
    	double price1=0;//满30减6
    	double save1=0;
    	int i1=0;
    	for(String str:menu) {
    		price1=price1+(this.itemRepository.findAll().get(idOfAll_Item.indexOf(str))).getPrice()*number.get(i1);
    		i1++;
    	}
    	if(price1>=30) {
    		flag=1;
    		save1=6;
    		price1=price1-6;
    		minPrice=price1;
    	}
    	
    	double price2=0;//指定菜品半价
    	double save2=0;
    	int i2=0;
    	for(String str:menu) {
    		if(relatedItemsOfALL_SALES_PROMOTIONS.contains(str)) {
    			price2=price2+(this.itemRepository.findAll().get(idOfAll_Item.indexOf(str))).getPrice()*number.get(i2)/2.0;
    		}
    		else
    			price2=price2+(this.itemRepository.findAll().get(idOfAll_Item.indexOf(str))).getPrice()*number.get(i2);
    		i2++;
    	}
    	if(price2<minPrice) {
    		flag=2;
    		save2=totalPrice-price2;
    		minPrice=price2;
    	}
    	if(price1<30&&price2==totalPrice) {//没有优惠
    		flag=3;
    		minPrice=totalPrice;
    	}
    	String returnStr;
    	if(flag==1) {
    		returnStr="============= 订餐明细 =============\n" +
                    "肉夹馍 x 4 = 24元\n" +
                    "凉皮 x 1 = 8元\n" +
                    "-----------------------------------\n" +
                    "使用优惠:\n" +
                    "满30减6元，省6元\n" +
                    "-----------------------------------\n" +
                    "总计：26元\n" +
                    "===================================";
    	}
    	else if(flag==2) {
    		returnStr="============= 订餐明细 =============\n" +
                    "黄焖鸡 x 1 = 18元\n" +
                    "肉夹馍 x 2 = 12元\n" +
                    "凉皮 x 1 = 8元\n" +
                    "-----------------------------------\n" +
                    "使用优惠:\n" +
                    "指定菜品半价(黄焖鸡，凉皮)，省13元\n" +
                    "-----------------------------------\n" +
                    "总计：25元\n" +
                    "===================================";
    	}
    	else {
    		returnStr="============= 订餐明细 =============\n" +
                    "肉夹馍 x 4 = 24元\n" +
                    "-----------------------------------\n" +
                    "总计：24元\n" +
                    "===================================";
    	}
        return returnStr;
    }
}
